#### Encoding ia a technique to convert categorical values to numerical encodings so that machime learning algorithms can understand it better

## One hot coding 
Each categorical value is represented as binary vector eg , consider color variable having red , green ., blue as values 

so if we use one hot encoding for color variables 
green=[1,0,0]
red=[0,1,0]
blue=[0,0,1]

Disadvantage= 
1.cannot be used with variables having a lot of values as the features will increase 
2. Also it creates sparse matricies , which leads to  overfitting

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df=pd.DataFrame(
    {
        'color':['red','blue','green','green','red','blue']
    }
)
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [6]:
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['color']]).toarray()
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [7]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [8]:
import seaborn as sns
tips=sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
encoded_sex=encoder.fit_transform(tips[['sex']]).toarray()
encoded_sex_df=pd.DataFrame(encoded_sex,columns=encoder.get_feature_names_out())
encoded_sex_df.head()

   sex_Female  sex_Male
0         1.0       0.0
1         0.0       1.0
2         0.0       1.0
3         0.0       1.0
4         1.0       0.0

In [15]:
del tips['sex']
pd.concat([tips,encoded_sex_df],axis=1)

     total_bill   tip smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61     No   Sun  Dinner     4         1.0       0.0
..          ...   ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00     No  Thur  Dinner     2         1.0       0.0

[244 rows x 8 columns]