### Creating Dataframe

In [3]:
import pandas as pd

In [6]:
# using a dictionary of lists

data={
    'name':['Dilpreet','Anmol','Andeep'],
    'age':[34,32,2],
    'city':['Bla','sgr','Bla']
    }
df=pd.DataFrame(data)
df

       name  age city
0  Dilpreet   34  Bla
1     Anmol   32  sgr
2    Andeep    2  Bla

### Accessing Data elements

In [12]:
print(df['name'])
print(df.loc[0])
print(df.iloc[0])

0    Dilpreet
1       Anmol
2      Andeep
Name: name, dtype: object
name    Dilpreet
age           34
city         Bla
Name: 0, dtype: object
name    Dilpreet
age           34
city         Bla
Name: 0, dtype: object

adding a column

In [13]:
df['salary']=[10000,2000,3000]
df

       name  age city  salary
0  Dilpreet   34  Bla   10000
1     Anmol   32  sgr    2000
2    Andeep    2  Bla    3000

In [16]:
# droping a column
df.drop('salary',axis=1,inplace=True)
df

       name  age city
0  Dilpreet   34  Bla
1     Anmol   32  sgr
2    Andeep    2  Bla