In [6]:
import pandas as pd 
df=pd.read_csv(r"C:\Users\Dilpreet\Downloads\employees.csv")
df.head()
df.tail()

    id   name   department    salary
25  26    Zoe  Engineering  110000.0
26  27  Aiden    Marketing       NaN
27  28  Bella      Finance   85000.0
28  29   Chen      Finance   70000.0
29  30   Diya  Engineering   55000.0

In [7]:
df.describe()

              id         salary
count  30.000000      28.000000
mean   15.500000   81964.285714
std     8.803408   31807.851515
min     1.000000   50000.000000
25%     8.250000   63750.000000
50%    15.500000   72500.000000
75%    22.750000   90000.000000
max    30.000000  200000.000000

In [9]:
df.dtypes

id              int64
name           object
department     object
salary        float64
dtype: object

In [11]:
# handling missing values 
df.isnull().sum()

id            0
name          0
department    0
salary        2
dtype: int64

In [14]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29    False
dtype: bool

In [15]:
df.isnull().any()

id            False
name          False
department    False
salary         True
dtype: bool

In [16]:
df1=df.fillna(0)
df1

    id   name   department    salary
0    1  Alice  Engineering   50000.0
1    2    Bob    Marketing   70000.0
2    3  Carol        Sales   65000.0
3    4  David  Engineering  150000.0
4    5    Eve      Finance   60000.0
5    6  Frank      Finance   90000.0
6    7  Grace  Engineering   50000.0
7    8  Heidi  Engineering   70000.0
8    9   Ivan        Sales  100000.0
9   10   Judy      Finance   50000.0
10  11   Karl      Finance   70000.0
11  12   Liam      Finance   90000.0
12  13   Mona        Sales       0.0
13  14   Nina      Finance   75000.0
14  15   Omar  Engineering   70000.0
15  16  Priya           HR   85000.0
16  17  Quinn    Marketing   65000.0
17  18   Ravi        Sales   85000.0
18  19   Sara  Engineering   60000.0
19  20    Tom           HR   60000.0
20  21    Uma    Marketing   85000.0
21  22    Vik      Finance   75000.0
22  23  Wendy  Engineering  200000.0
23  24   Xena           HR  110000.0
24  25  Yusuf  Engineering   90000.0
25  26    Zoe  Engineering  110000.0
26  27  Aiden    Marketing       0.0
27  28  Bella      Finance   85000.0
28  29   Chen      Finance   70000.0
29  30   Diya  Engineering   55000.0

In [19]:
# filling missing values qith mean 
df['salary_fill_na']=df['salary'].fillna(df['salary'].mean())
df

    id   name   department    salary  salary_fill_na
0    1  Alice  Engineering   50000.0    50000.000000
1    2    Bob    Marketing   70000.0    70000.000000
2    3  Carol        Sales   65000.0    65000.000000
3    4  David  Engineering  150000.0   150000.000000
4    5    Eve      Finance   60000.0    60000.000000
5    6  Frank      Finance   90000.0    90000.000000
6    7  Grace  Engineering   50000.0    50000.000000
7    8  Heidi  Engineering   70000.0    70000.000000
8    9   Ivan        Sales  100000.0   100000.000000
9   10   Judy      Finance   50000.0    50000.000000
10  11   Karl      Finance   70000.0    70000.000000
11  12   Liam      Finance   90000.0    90000.000000
12  13   Mona        Sales       NaN    81964.285714
13  14   Nina      Finance   75000.0    75000.000000
14  15   Omar  Engineering   70000.0    70000.000000
15  16  Priya           HR   85000.0    85000.000000
16  17  Quinn    Marketing   65000.0    65000.000000
17  18   Ravi        Sales   85000.0    85000.000000
18  19   Sara  Engineering   60000.0    60000.000000
19  20    Tom           HR   60000.0    60000.000000
20  21    Uma    Marketing   85000.0    85000.000000
21  22    Vik      Finance   75000.0    75000.000000
22  23  Wendy  Engineering  200000.0   200000.000000
23  24   Xena           HR  110000.0   110000.000000
24  25  Yusuf  Engineering   90000.0    90000.000000
25  26    Zoe  Engineering  110000.0   110000.000000
26  27  Aiden    Marketing       NaN    81964.285714
27  28  Bella      Finance   85000.0    85000.000000
28  29   Chen      Finance   70000.0    70000.000000
29  30   Diya  Engineering   55000.0    55000.000000

In [20]:
df1.rename(columns={'name':'Name'})

    id   Name   department    salary
0    1  Alice  Engineering   50000.0
1    2    Bob    Marketing   70000.0
2    3  Carol        Sales   65000.0
3    4  David  Engineering  150000.0
4    5    Eve      Finance   60000.0
5    6  Frank      Finance   90000.0
6    7  Grace  Engineering   50000.0
7    8  Heidi  Engineering   70000.0
8    9   Ivan        Sales  100000.0
9   10   Judy      Finance   50000.0
10  11   Karl      Finance   70000.0
11  12   Liam      Finance   90000.0
12  13   Mona        Sales       0.0
13  14   Nina      Finance   75000.0
14  15   Omar  Engineering   70000.0
15  16  Priya           HR   85000.0
16  17  Quinn    Marketing   65000.0
17  18   Ravi        Sales   85000.0
18  19   Sara  Engineering   60000.0
19  20    Tom           HR   60000.0
20  21    Uma    Marketing   85000.0
21  22    Vik      Finance   75000.0
22  23  Wendy  Engineering  200000.0
23  24   Xena           HR  110000.0
24  25  Yusuf  Engineering   90000.0
25  26    Zoe  Engineering  110000.0
26  27  Aiden    Marketing       0.0
27  28  Bella      Finance   85000.0
28  29   Chen      Finance   70000.0
29  30   Diya  Engineering   55000.0

In [21]:
df1.dtypes

id              int64
name           object
department     object
salary        float64
dtype: object

In [22]:
df1['id']=df['id'].fillna(df['id'].mode()).astype(object)

In [23]:
df1.dtypes

id             object
name           object
department     object
salary        float64
dtype: object

In [ ]:
df['salary']=df['salary'].apply(lambda x:x*2).sum()

In [25]:
df.head()

   id   name   department    salary  salary_fill_na
0   1  Alice  Engineering  100000.0         50000.0
1   2    Bob    Marketing  140000.0         70000.0
2   3  Carol        Sales  130000.0         65000.0
3   4  David  Engineering  300000.0        150000.0
4   5    Eve      Finance  120000.0         60000.0

In [41]:
# Data aggregatinag and grouping 

grouped_sal=df.groupby(['department','name'])['salary'].sum()
sorted_df=grouped_sal.sort_values(ascending=False)
sorted_df
grouped_sal

department   name
Engineering  Alice    100000.0
             David    300000.0
             Diya     110000.0
             Grace    100000.0
             Heidi    140000.0
             Omar     140000.0
             Sara     120000.0
             Wendy    400000.0
             Yusuf    180000.0
             Zoe      220000.0
Finance      Bella    170000.0
             Chen     140000.0
             Eve      120000.0
             Frank    180000.0
             Judy     100000.0
             Karl     140000.0
             Liam     180000.0
             Nina     150000.0
             Vik      150000.0
HR           Priya    170000.0
             Tom      120000.0
             Xena     220000.0
Marketing    Aiden         0.0
             Bob      140000.0
             Quinn    130000.0
             Uma      170000.0
Sales        Carol    130000.0
             Ivan     200000.0
             Mona          0.0
             Ravi     170000.0
Name: salary, dtype: float64