In [1]:
# importing required libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
# Reading the dataset
flight_df=pd.read_excel(r"C:\Study_Material\Python_Codes_and_practice\Python_Practice\Feature_Engineering\EDA\flight_price.xlsx")
flight_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [4]:
flight_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [5]:
# checking shape , info , descriptive statistics 
print(flight_df.shape)
print(flight_df.info())
print(flight_df.describe())

(10683, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB
None
              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [6]:
# checking Missing values 
flight_df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [7]:
flight_df[flight_df.duplicated()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
683,Jet Airways,1/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,14:35,04:25 02 Jun,13h 50m,2 stops,No info,13376
1061,Air India,21/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 22 May,21h 15m,2 stops,No info,10231
1348,Air India,18/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 19 May,26h,2 stops,No info,12392
1418,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,05:30,04:25 07 Jun,22h 55m,2 stops,In-flight meal not included,10368
1674,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,18:25,21:20,2h 55m,non-stop,No info,7303
...,...,...,...,...,...,...,...,...,...,...,...
10594,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 28 Jun,13h 30m,2 stops,No info,12819
10616,Jet Airways,1/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 02 Jun,26h 55m,2 stops,No info,13014
10634,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 07 Jun,26h 55m,2 stops,In-flight meal not included,11733
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
10673,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704

In [9]:
flight_df.drop_duplicates(inplace=True)

In [10]:
flight_df.shape

(10463, 11)

## Starting with Feature Engineering

In [11]:
flight_df.head(1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897

In [18]:
# separating Datein to separate dates , months and year columns 
flight_df['Date']=flight_df['Date_of_Journey'].str.split("/").str[0].astype(int)
flight_df['Month']=flight_df['Date_of_Journey'].str.split("/").str[1].astype(int)
flight_df['Year']=flight_df['Date_of_Journey'].str.split("/").str[2].astype(int)
flight_df.head(1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019

In [19]:
flight_df.info()
#  month , date and year variables ae still oin object -string format , numeric conversion is needed

<class 'pandas.core.frame.DataFrame'>
Index: 10463 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10463 non-null  object
 1   Date_of_Journey  10463 non-null  object
 2   Source           10463 non-null  object
 3   Destination      10463 non-null  object
 4   Route            10462 non-null  object
 5   Dep_Time         10463 non-null  object
 6   Arrival_Time     10463 non-null  object
 7   Duration         10463 non-null  object
 8   Total_Stops      10462 non-null  object
 9   Additional_Info  10463 non-null  object
 10  Price            10463 non-null  int64
 11  Date             10463 non-null  int64
 12  Month            10463 non-null  int64
 13  Year             10463 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.2+ MB

In [ ]:
del flight_df['Date_of_Journey']
# or  we can use df.drop(variable , axis=1,inplace=True)

In [21]:
flight_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019

In [28]:
# splitting time from date in arrival time 
flight_df['Arrival_Time']=flight_df['Arrival_Time'].apply(lambda x:x.split(" ")[0])

In [29]:
# Handling Arrival_Time
flight_df['arrival_hour']=flight_df['Arrival_Time'].str.split(":").str[0].astype(int)
flight_df['arrival_min']=flight_df['Arrival_Time'].str.split(":").str[1].astype(int)
flight_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,1,10

In [30]:
del flight_df['Arrival_Time']

In [33]:
flight_df['departure_hour']=flight_df['Dep_Time'].str.split(":").str[0].astype(int)
flight_df['departure_min']=flight_df['Dep_Time'].str.split(":").str[1].astype(int)
flight_df.drop('Dep_Time',axis=1,inplace=True)
flight_df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min,departure_hour,departure_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20

In [37]:
flight_df['Total_Stops'].unique()

array([0, 2, 1, 3, 4])

In [35]:
flight_df['Total_Stops']=flight_df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, np.nan:1, '4 stops':4})

In [36]:
flight_df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min,departure_hour,departure_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20

In [60]:
# handling duration 
flight_df['d_hr']=flight_df['Duration'].str.split(" ").str[0].str.split("h").str[0]
# handling duration 
flight_df['d_min']=flight_df['Duration'].str.split(" ").str[1].str.split("m").str[0]

In [ ]:
flight_df = flight_df[flight_df['d_hr'] != '5m']

# Convert duration columns to numeric and fill missing minutes with 0
flight_df['d_hr'] = flight_df['d_hr'].astype(int)
flight_df['d_min'] = flight_df['d_min'].fillna(0).astype(int)

# Calculate total duration in minutes
flight_df['duration_in_minutes'] = (flight_df['d_hr'] * 60) + flight_df['d_min']
flight_df.drop(['Duration','d_hr','d_min'],axis=1,inplace=True)
flight_df.head(2)

In [72]:
flight_df.drop(['Route'],axis=1,inplace=True)

In [73]:
flight_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,arrival_hour,arrival_min,departure_hour,departure_min,duration_in_minutes
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,13,15,5,50,445
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,23,30,18,5,325
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,21,35,16,50,285

In [77]:
# checking unique values of all categorical variables
for col in flight_df.columns:
    if flight_df[col].dtype=='object':
        print(f"unique values for {col} are --->{flight_df[col].unique()}\n")

unique values for Airline are --->['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']

unique values for Source are --->['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']

unique values for Destination are --->['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']

unique values for Additional_Info are --->['No info' 'In-flight meal not included' 'No check-in baggage included'
 '1 Short layover' 'No Info' '1 Long layover' 'Change airports'
 'Business class' 'Red-eye flight' '2 Long layover']

In [79]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder=OneHotEncoder()

In [89]:
cat_columns=[col for col in flight_df.columns if flight_df[col].dtype=='object' ]
encodedcat_df=pd.DataFrame(cat_encoder.fit_transform(flight_df[cat_columns]).toarray(),columns=cat_encoder.get_feature_names_out())

In [93]:
flight_transformed_df=pd.concat([flight_df,encodedcat_df],axis=1)
flight_transformed_df.drop(cat_columns,axis=1,inplace=True)
print(flight_transformed_df.shape)
flight_transformed_df.head()

(10671, 43)

,Total_Stops,Price,Date,Month,Year,arrival_hour,arrival_min,departure_hour,departure_min,duration_in_minutes,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,170.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2.0,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,445.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2.0,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,25.0,1140.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,5.0,325.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,50.0,285.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [94]:
flight_transformed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10671 entries, 0 to 10453
Data columns (total 43 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Total_Stops                                   10462 non-null  float64
 1   Price                                         10462 non-null  float64
 2   Date                                          10462 non-null  float64
 3   Month                                         10462 non-null  float64
 4   Year                                          10462 non-null  float64
 5   arrival_hour                                  10462 non-null  float64
 6   arrival_min                                   10462 non-null  float64
 7   departure_hour                                10462 non-null  float64
 8   departure_min                                 10462 non-null  float64
 9   duration_in_minutes                           10462 non-null  float64
 10  Airline_Air Asia                              10462 non-null  float64
 11  Airline_Air India                             10462 non-null  float64
 12  Airline_GoAir                                 10462 non-null  float64
 13  Airline_IndiGo                                10462 non-null  float64
 14  Airline_Jet Airways                           10462 non-null  float64
 15  Airline_Jet Airways Business                  10462 non-null  float64
 16  Airline_Multiple carriers                     10462 non-null  float64
 17  Airline_Multiple carriers Premium economy     10462 non-null  float64
 18  Airline_SpiceJet                              10462 non-null  float64
 19  Airline_Trujet                                10462 non-null  float64
 20  Airline_Vistara                               10462 non-null  float64
 21  Airline_Vistara Premium economy               10462 non-null  float64
 22  Source_Banglore                               10462 non-null  float64
 23  Source_Chennai                                10462 non-null  float64
 24  Source_Delhi                                  10462 non-null  float64
 25  Source_Kolkata                                10462 non-null  float64
 26  Source_Mumbai                                 10462 non-null  float64
 27  Destination_Banglore                          10462 non-null  float64
 28  Destination_Cochin                            10462 non-null  float64
 29  Destination_Delhi                             10462 non-null  float64
 30  Destination_Hyderabad                         10462 non-null  float64
 31  Destination_Kolkata                           10462 non-null  float64
 32  Destination_New Delhi                         10462 non-null  float64
 33  Additional_Info_1 Long layover                10462 non-null  float64
 34  Additional_Info_1 Short layover               10462 non-null  float64
 35  Additional_Info_2 Long layover                10462 non-null  float64
 36  Additional_Info_Business class                10462 non-null  float64
 37  Additional_Info_Change airports               10462 non-null  float64
 38  Additional_Info_In-flight meal not included   10462 non-null  float64
 39  Additional_Info_No Info                       10462 non-null  float64
 40  Additional_Info_No check-in baggage included  10462 non-null  float64
 41  Additional_Info_No info                       10462 non-null  float64
 42  Additional_Info_Red-eye flight                10462 non-null  float64
dtypes: float64(43)
memory usage: 3.6 MB